setw -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
# Use 'r' to toggle block selection mode on/off
bind -T copy-mode-vi r send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

set -g base-index 1
set -g renumber-windows on
set -g default-terminal 'screen-256color'

bind c new-window -c '#{pane_current_path}' -a -t '{next}'
bind -n M-c new-window -c '#{pane_current_path}' -a -t '{next}'
bind -n M-z resize-pane -Z

bind x confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind X confirm-before -p "kill-session #S? (y/n)" kill-session
bind N command-prompt -p "New Session Name:" "new-session -s '%%'"
bind '$' command-prompt -I "#S" { rename-session "%%" }
bind ',' command-prompt -I "#W" { rename-window "%%" }
bind O confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"



bind d detach
bind C-d detach
bind : command-prompt

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

bind -n M-V split-window -h -c '#{pane_current_path}'
bind -n M-H split-window -v -c  '#{pane_current_path}'
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
set -g prefix C-z
bind C-z send-prefix
bind r {
  source-file ~/.tmux.conf
  display 'config reloaded'
}

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-n next-window
bind -n M-N swap-window -d -t '{next}'
bind -n M-p previous-window
bind -n M-P swap-window -d -t '{previous}'

bind -n M-s choose-tree -Zs -f '#{?#{m:_popup_*,#S},0,1}' -O name
bind -n M-L break-pane -a -t '{next}'
 
# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on


# don't rename windows automatically
set-option -g allow-rename off


